1. Импортировать NumPy под именем np

In [2]:
import numpy as np

2. Напечатать версию и конфигурацию

In [3]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELSI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/DELSI/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELSI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

3. Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Создать вектор размера 10, заполненный единицами

In [5]:
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Создать вектор размера 10, заполненный числом 2.5

In [6]:
c=np.full(10,2.5)
print(c)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6. Как получить документацию о функции numpy.add из командной строки?

In [7]:
-c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-7-bf39acddc0fc>, line 1)

7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
d=np.zeros(10)
d[5]=1
print(d)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


8. Создать вектор со значениями от 10 до 49

In [9]:
e=np.arange(10,50)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Развернуть вектор (первый становится последним)

In [10]:
print(e[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [11]:
g=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
h=np.array([1,2,0,0,4,0])
print(np.nonzero(h))

(array([0, 1, 4], dtype=int64),)


12. Создать массив 3x3x3 со случайными значениями

In [13]:
k=np.random.random((3,3,3))
print(k)

[[[0.22103899 0.75429687 0.45320788]
  [0.70422736 0.71526754 0.39498228]
  [0.8610739  0.74327475 0.10196797]]

 [[0.59654097 0.68785671 0.66181287]
  [0.00616692 0.81640726 0.21855643]
  [0.10267288 0.51120232 0.93384397]]

 [[0.84046995 0.08798811 0.77367658]
  [0.97140372 0.34638889 0.35764746]
  [0.99007167 0.5918296  0.21151385]]]


13. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [14]:
l=np.random.random((10,10))
print(l,np.max(l),np.min(l))

[[0.69960639 0.92894062 0.24888084 0.32934973 0.2427673  0.42961682
  0.79548135 0.10856424 0.92866808 0.68084762]
 [0.22926839 0.22864572 0.58350486 0.57174366 0.59978552 0.44057244
  0.04052331 0.23442286 0.06461651 0.67437947]
 [0.74833055 0.01824983 0.55049989 0.99254829 0.87616171 0.66581295
  0.76923747 0.10687712 0.61083354 0.36681537]
 [0.53652394 0.79534183 0.76416279 0.78062853 0.29450852 0.45925515
  0.92659826 0.0650199  0.70422848 0.12221083]
 [0.14877239 0.58660968 0.82799324 0.10815517 0.79315911 0.16260092
  0.46628303 0.59338596 0.69901022 0.23183796]
 [0.70707105 0.02934756 0.10434825 0.09635433 0.63012132 0.89390794
  0.26166447 0.94353525 0.75296581 0.76500602]
 [0.29269507 0.47042046 0.88018329 0.29004551 0.2640492  0.00376125
  0.00772809 0.90297187 0.23102526 0.31926598]
 [0.57856157 0.363149   0.04690809 0.60059665 0.87322711 0.81257513
  0.83158051 0.87790407 0.06577675 0.44624674]
 [0.28207307 0.15106888 0.01383544 0.59935475 0.1023667  0.52328485
  0.67408045

14. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [15]:
m=np.random.random(30)
print(m,np.mean(m))

[0.22877889 0.69021806 0.18129939 0.76194295 0.01455101 0.28562907
 0.83927849 0.64298742 0.28075028 0.8398837  0.83395193 0.40953351
 0.44335668 0.57820302 0.96891222 0.187433   0.27840219 0.90941344
 0.14973256 0.21102728 0.64946087 0.81647173 0.2498821  0.44712932
 0.93976225 0.79873593 0.46439645 0.38280395 0.45294078 0.53948686] 0.5158785102251188


15. Создать матрицу с 0 внутри, и 1 на границах

In [16]:
n=np.ones((int(input()),int(input())))
n[1:-1,1:-1]=0
print(n)

4
4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


16. Выяснить результат следующих выражений
(	0 * np.nan
	np.nan == np.nan
	np.inf > np.nan
	np.nan - np.nan)

In [17]:
0*np.nan

nan

In [18]:
np.nan == np.nan

False

In [19]:
np.inf > np.nan

False

In [20]:
np.nan - np.nan

nan

17. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [21]:
o = np.diag(np.arange(1, 5), k=-1)
print(o)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


18. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [22]:
p=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if ((i+j)%2==0):
            p[i,j]=0    
print(p)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


19. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [23]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


20. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [24]:
r=np.array([[0,1], [1,0]])
print(np.tile(r,[4,4]))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
