Московский Авиационный Институт  
                                  (Национальный Исследовательский Университет)  



Кафедра 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»        



                                        -------------------------------
                                        Лабораторная работа по NumPy №2  
                                        -------------------------------    



                                                                            Группа: М8О-103М-20  
                                                                            Студент: Галюгин Алексей Дмитриевич  
                                                                            Преподаватель: Поповкин Александр Викторович  



                                                 Москва, 2020  

In [3]:
import numpy as np
import scipy.spatial

Перемножить матрицы 5x3 и 3x2

In [5]:
a=np.random.random((5,3))
b=np.random.random((3,2))
c=np.dot(a,b)
print(c)

[[0.77304546 0.57296309]
 [0.88138131 0.80641567]
 [0.79524149 0.65280646]
 [1.22048986 1.05031184]
 [1.22320607 1.09329398]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [14]:
b=np.array([3,4,1,7,9,8,6,12,4])
for i in range(len(b)):
    if(b[i]>3)&(b[i]<8):
        b[i]=b[i]*(-1)
print(b)


[ 3 -4  1 -7  9  8 -6 12 -4]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [16]:
import random
c=np.ones((5,5))
for i in range(5):
    for j in range(5):
        c[i,j]=random.uniform(0, 4)
print(c)        

[[1.17055843 1.60814725 1.92333419 2.57733757 3.48200678]
 [0.39029251 2.50107543 1.44725173 2.00204613 2.0301166 ]
 [1.89295742 0.86729548 0.87930834 0.62938193 1.82734813]
 [1.71222834 1.97288655 0.51267836 3.00243397 2.06146303]
 [3.8726742  0.14905533 0.35573223 1.61620568 2.13275852]]


Есть генератор, сделать с его помощью массив

In [66]:
def gen():
    for i in range(10):
        yield i*8-10
d=np.fromiter(gen(),dtype=int)    
print(d)

[-10  -2   6  14  22  30  38  46  54  62]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [27]:
e=np.linspace(0.1,0.5,10)
print(e)

[0.1        0.14444444 0.18888889 0.23333333 0.27777778 0.32222222
 0.36666667 0.41111111 0.45555556 0.5       ]


Отсортировать вектор

In [28]:
f=np.random.random(10)
f.sort()
print(f)

[0.10652989 0.17331358 0.38709359 0.42630073 0.47745496 0.51560992
 0.64557611 0.77719528 0.96349509 0.97151496]


Проверить, одинаковы ли 2 numpy массива

In [29]:
g=np.random.random(10)
h=np.random.random(10)
print(np.allclose(g,h))

False


Сделать массив неизменяемым

In [31]:
i=np.random.random(10)
i = tuple(i)

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [39]:
k = np.random.random((10,2))
print(k)
l=k[:,0]
m=k[:,1]
n=np.hypot(l,m)
o=np.arctan2(l,m)*180/np.pi
print('полярные радиусы равны',n)
print('полярные углы равны',o)

[[0.59258274 0.25852062]
 [0.56870311 0.21178901]
 [0.81885656 0.76833347]
 [0.05761299 0.02630972]
 [0.72179656 0.7783996 ]
 [0.55185833 0.53572098]
 [0.32071404 0.66615633]
 [0.08458696 0.56735549]
 [0.45325814 0.08221474]
 [0.190765   0.88658366]]
полярные радиусы равны [0.64651931 0.60685897 1.12288129 0.06333607 1.06155368 0.76911936
 0.73933873 0.57362637 0.46065411 0.90687478]
полярные углы равны [66.43024364 69.5743181  46.82321123 65.45557113 42.83923077 45.85008429
 25.70800594  8.47975995 79.71911754 12.14311518]


Заменить максимальный элемент на ноль

In [42]:
l=np.random.random(10)
print(l)
l[l.argmax()]=0
print(l)

[0.28878666 0.94970583 0.83417116 0.23292801 0.66967277 0.48809752
 0.57189511 0.63444336 0.37928791 0.35630456]
[0.28878666 0.         0.83417116 0.23292801 0.66967277 0.48809752
 0.57189511 0.63444336 0.37928791 0.35630456]


Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [68]:
xy=np.zeros((10,10),[('coordx',float),('coordy',float)])
xy['coordx'], xy['coordy']=np.meshgrid(np.random.random(10),
                             np.random.random(10))
print(xy)

[[(0.04718867, 0.29200952) (0.18169897, 0.29200952)
  (0.3985587 , 0.29200952) (0.54968016, 0.29200952)
  (0.80014026, 0.29200952) (0.39999368, 0.29200952)
  (0.94427117, 0.29200952) (0.2957367 , 0.29200952)
  (0.88680204, 0.29200952) (0.68470815, 0.29200952)]
 [(0.04718867, 0.89759101) (0.18169897, 0.89759101)
  (0.3985587 , 0.89759101) (0.54968016, 0.89759101)
  (0.80014026, 0.89759101) (0.39999368, 0.89759101)
  (0.94427117, 0.89759101) (0.2957367 , 0.89759101)
  (0.88680204, 0.89759101) (0.68470815, 0.89759101)]
 [(0.04718867, 0.36221845) (0.18169897, 0.36221845)
  (0.3985587 , 0.36221845) (0.54968016, 0.36221845)
  (0.80014026, 0.36221845) (0.39999368, 0.36221845)
  (0.94427117, 0.36221845) (0.2957367 , 0.36221845)
  (0.88680204, 0.36221845) (0.68470815, 0.36221845)]
 [(0.04718867, 0.75276716) (0.18169897, 0.75276716)
  (0.3985587 , 0.75276716) (0.54968016, 0.75276716)
  (0.80014026, 0.75276716) (0.39999368, 0.75276716)
  (0.94427117, 0.75276716) (0.2957367 , 0.75276716)
  (0.8868

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [75]:
x=np.arange(4)
y=x+6
z=np.ones((4,4))
print(x)
print(y)
for i in range(0,len(x)):
    for j in range(0,len(y)):
        z[i,j]=1/(x[i]-y[j])
print(z)        

[0 1 2 3]
[6 7 8 9]
[[-0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.25       -0.2        -0.16666667 -0.14285714]
 [-0.33333333 -0.25       -0.2        -0.16666667]]


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [2]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


Напечатать все значения в массиве

In [78]:
r=np.random.random(10)
print(r)
for i in range(0,len(r)):
    print(r[i])

[0.17949078 0.77170086 0.37962705 0.52245293 0.48077618 0.36330504
 0.28614656 0.14452712 0.15665062 0.31679927]
0.17949077849887052
0.7717008604781915
0.37962705493311366
0.5224529281951966
0.4807761757341733
0.36330504463644187
0.28614655707666936
0.1445271167332669
0.15665062054693324
0.3167992657111377


Найти ближайшее к заданному значению число в заданном массиве

In [83]:
n=np.arange(10)
k=float(input())
min=np.abs(k-n[0])
for i in range(0,len(n)):
    if ((min)>(np.abs(k-n[i]))):
        min=(np.abs(k-n[i]))
        l=n[i]
print(l)
        

5.8
6


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [64]:
m=np.random.random((100,2))
x=scipy.spatial.distance.cdist(m,m)
print(m)
print(x)

[[0.74698504 0.36512258]
 [0.95026616 0.6541125 ]
 [0.88891472 0.20519567]
 [0.65458817 0.10353364]
 [0.38391393 0.37970812]
 [0.16772175 0.07545036]
 [0.53311718 0.98315899]
 [0.18975755 0.07677968]
 [0.63952702 0.36028269]
 [0.91195096 0.72986283]
 [0.30205964 0.46665093]
 [0.96763358 0.20717528]
 [0.64866112 0.95187363]
 [0.16059463 0.88582549]
 [0.33020403 0.28099392]
 [0.57542772 0.86133375]
 [0.02145701 0.9786406 ]
 [0.60886433 0.27137537]
 [0.92300162 0.81822025]
 [0.88942898 0.44631561]
 [0.84792734 0.16270314]
 [0.98111011 0.43890031]
 [0.18265011 0.50661528]
 [0.92143588 0.08733504]
 [0.44046408 0.12150849]
 [0.13868323 0.32602531]
 [0.23078264 0.17498899]
 [0.32688943 0.34844129]
 [0.19489193 0.0055838 ]
 [0.99839789 0.02059872]
 [0.92707944 0.66493493]
 [0.6037088  0.4660388 ]
 [0.3968549  0.60696899]
 [0.33139216 0.82604957]
 [0.32465713 0.81996815]
 [0.15220499 0.66689845]
 [0.78665995 0.45014623]
 [0.98979075 0.49278487]
 [0.83599896 0.13533956]
 [0.48404513 0.22314516]


Преобразовать массив из float в int

In [14]:
x=np.linspace(0,2,10)
print(x)
x=x.astype(int)
print(x)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
[0 0 0 0 0 1 1 1 1 2]


Дан файл:
1,2,3,4,5
6,,,7,8
,,9,10,11
Как прочитать его?

In [ ]:
k=np.genfromtxt("название файла", delimiter=",")

Каков эквивалент функции enumerate для numpy массивов?

In [19]:
x=np.arange(9).reshape(3,3)
print(x)
for index,value in np.ndenumerate(x):
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Сформировать 2D массив с распределением Гаусса

In [23]:
x=np.random.random((5,5))
y=np.random.random((5,5))
z=np.hypot(x,y)
s=1
n=0
gauss=np.exp(-((z-n)**2/(2.0*s**2)))
print(gauss)

[[0.70883189 0.89229006 0.90015541 0.6431628  0.6583158 ]
 [0.84596334 0.60892363 0.46923077 0.77201434 0.61775029]
 [0.91546952 0.65112442 0.8733335  0.74111895 0.78899077]
 [0.79757906 0.81378394 0.71750296 0.97752596 0.51804998]
 [0.84811037 0.70878061 0.96422123 0.77448826 0.68619622]]


Случайно расположить p элементов в 2D массив

In [29]:
x=np.zeros((4,4))
p=3
y=np.put(x,np.random.choice(range(4*4),p),1)
print(x)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [68]:
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
q=np.ones((3,3))
for i in range(0,3):
    l=0
    p=0
    for j in range(0,3):
        p=p+1
        l=l+x[i,j]
    mean=l/p
    
    for m in range(0,3):
        q[i,m]=x[i,m] - mean
print(q)
        
        
        

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


Отсортировать матрицу по n-ому столбцу

In [71]:
x=np.random.random((3,3))
n=int(input())
print(x)
print(x[x[:,n].argsort()])

2
[[0.3286648  0.70011774 0.08539179]
 [0.58994225 0.95041577 0.77596209]
 [0.02248132 0.44856527 0.70358768]]
[[0.3286648  0.70011774 0.08539179]
 [0.02248132 0.44856527 0.70358768]
 [0.58994225 0.95041577 0.77596209]]


Определить, есть ли в 2D массиве нулевые столбцы

In [13]:
x=np.array([[1,0,2],[0,0,3],[1,0,9]])
for i in range(0,3):
    n=0
    for j in range(0,3):
        if (x[j,i]==0):
            n=n+1
    if (n==3):
        print("В матрице есть нулевой столбец")
        break
if (n!=3):
    print("В матрице нет нулевых столбцов")
        
        

В матрице есть нулевой столбец


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [27]:
x=np.random.randint(0,10,10)
print(x)
y=np.random.randint(0,len(x)-1,20)
print(y)
z=np.unique(y)
print(z)
for i in range(0,len(z)):
    x[z[i]]=x[z[i]]+1
print(x)    

[9 4 5 8 0 5 2 7 8 9]
[1 5 3 6 1 6 7 2 5 0 6 4 1 7 6 0 7 2 4 6]
[0 1 2 3 4 5 6 7]
[10  5  6  9  1  6  3  8  8  9]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [45]:
w=8
h=8
x=np.random.randint(0, 2, (h,w,3))
print(x)
y=x[...,0]*256*256+x[...,1]*256+x[...,2] 
print(len(np.unique(y)))

[[[0 1 0]
  [1 1 1]
  [1 0 1]
  [0 0 1]
  [1 0 0]
  [0 0 1]
  [0 0 1]
  [0 1 0]]

 [[1 1 0]
  [1 1 0]
  [1 0 0]
  [0 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]
  [1 0 1]]

 [[0 0 1]
  [0 0 0]
  [1 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 1]
  [0 0 0]
  [0 1 1]]

 [[1 1 0]
  [1 0 1]
  [1 1 1]
  [1 1 1]
  [0 0 1]
  [1 0 0]
  [0 0 0]
  [0 1 0]]

 [[1 0 1]
  [1 0 1]
  [1 1 1]
  [0 1 1]
  [1 1 1]
  [0 0 0]
  [1 1 0]
  [1 0 0]]

 [[1 1 1]
  [0 1 1]
  [1 0 0]
  [1 0 0]
  [1 0 1]
  [1 0 0]
  [1 0 0]
  [1 1 0]]

 [[1 1 0]
  [1 0 1]
  [1 1 1]
  [1 0 1]
  [1 0 1]
  [0 0 0]
  [0 1 1]
  [1 0 1]]

 [[0 1 0]
  [1 1 0]
  [0 0 0]
  [1 0 0]
  [1 1 1]
  [0 1 1]
  [0 1 1]
  [0 0 0]]]
8


Дан четырехмерный массив, посчитать сумму по последним двум осям

In [63]:
x=np.random.randint(0,10, (3,4,3,4))
print(x)
print(x.shape[:-2])
y=x.reshape(x.shape[:-2]+(-1,))
print(y)
z=y.sum(axis=-1)
print(z)

[[[[8 7 9 1]
   [6 4 5 3]
   [1 7 4 2]]

  [[4 0 6 8]
   [6 2 3 5]
   [3 7 3 6]]

  [[4 0 4 1]
   [6 9 0 5]
   [2 2 4 4]]

  [[7 3 6 5]
   [8 1 7 3]
   [4 4 7 6]]]


 [[[7 0 0 6]
   [1 6 0 8]
   [1 7 8 9]]

  [[2 1 6 3]
   [2 6 5 0]
   [4 9 0 1]]

  [[9 4 2 7]
   [7 5 5 2]
   [9 9 4 0]]

  [[3 4 0 2]
   [8 5 7 7]
   [6 5 0 6]]]


 [[[5 9 7 3]
   [6 9 8 6]
   [3 0 8 1]]

  [[0 7 2 4]
   [2 9 1 9]
   [2 7 9 9]]

  [[0 9 1 2]
   [0 3 1 1]
   [6 3 9 7]]

  [[7 6 5 7]
   [9 2 0 2]
   [8 0 8 8]]]]
(3, 4)
[[[8 7 9 1 6 4 5 3 1 7 4 2]
  [4 0 6 8 6 2 3 5 3 7 3 6]
  [4 0 4 1 6 9 0 5 2 2 4 4]
  [7 3 6 5 8 1 7 3 4 4 7 6]]

 [[7 0 0 6 1 6 0 8 1 7 8 9]
  [2 1 6 3 2 6 5 0 4 9 0 1]
  [9 4 2 7 7 5 5 2 9 9 4 0]
  [3 4 0 2 8 5 7 7 6 5 0 6]]

 [[5 9 7 3 6 9 8 6 3 0 8 1]
  [0 7 2 4 2 9 1 9 2 7 9 9]
  [0 9 1 2 0 3 1 1 6 3 9 7]
  [7 6 5 7 9 2 0 2 8 0 8 8]]]
[[57 53 41 61]
 [53 39 63 53]
 [65 61 42 62]]


Найти диагональные элементы произведения матриц

In [48]:
x=np.array([[1,0,2],[0,0,3],[1,0,9]])
y=np.array([[4,5,3],[7,8,9],[5,6,1]])
np.diag(np.dot(x,y))

array([14, 18, 12])