Московский Авиационный Институт  
                                  (Национальный Исследовательский Университет)  



Кафедра 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»        



                                        -------------------------------
                                        Лабораторная работа по NumPy №3  
                                        -------------------------------    



                                                                            Группа: М8О-103М-20  
                                                                            Студент: Галюгин Алексей Дмитриевич  
                                                                            Преподаватель: Поповкин Александр Викторович  



                                                 Москва, 2020  

In [3]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [163]:
x=np.array([1,2,3,4,5])
y=np.ones(len(x)*4)
for i in range(0,len(x)*4):
    if (i%4==0):
        y[i]=x[i//4]
    else:
        y[i]=0
print(y)        

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


Поменять 2 строки в матрице

In [8]:
x=np.array([[1,0,2],[0,0,3],[1,0,9]])
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[1 0 2]
 [0 0 3]
 [1 0 9]]
[[0 0 3]
 [1 0 2]
 [1 0 9]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [131]:
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F)
F = F.reshape(len(F)*3,2)
print(F)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[[34 96 65]
 [ 8 32 58]
 [25 39 32]
 [12 68 72]
 [71 66 89]
 [63 15 45]
 [71 93 31]
 [66 54 98]
 [51 77 50]
 [24 21 56]]
[[34 96 96 65 65 34]
 [ 8 32 32 58 58  8]
 [25 39 39 32 32 25]
 [12 68 68 72 72 12]
 [71 66 66 89 89 71]
 [63 15 15 45 45 63]
 [71 93 93 31 31 71]
 [66 54 54 98 98 66]
 [51 77 77 50 50 51]
 [24 21 21 56 56 24]]
[[34 96]
 [96 65]
 [65 34]
 [ 8 32]
 [32 58]
 [58  8]
 [25 39]
 [39 32]
 [32 25]
 [12 68]
 [68 72]
 [72 12]
 [71 66]
 [66 89]
 [89 71]
 [63 15]
 [15 45]
 [45 63]
 [71 93]
 [93 31]
 [31 71]
 [66 54]
 [54 98]
 [98 66]
 [51 77]
 [77 50]
 [50 51]
 [24 21]
 [21 56]
 [56 24]]
[( 8, 32) ( 8, 58) (12, 68) (12, 72) (15, 45) (15, 63) (21, 24) (21, 56)
 (24, 56) (25, 32) (25, 39) (31, 71) (31, 93) (32, 39) (32, 58) (34, 65)
 (34, 96) (45, 63) (50, 51) (50, 77) (51, 77) (54, 66) (54, 98) (65, 96)
 (66, 71) (66, 89) (66, 98) (68, 72) (71, 89) (71, 93)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [132]:
a=np.bincount([1,1,2,3,4,4,6])
b=np.repeat(np.arange(len(a)), a)
print(b)


[1 1 2 3 4 4 6]


Посчитать среднее, используя плавающее окно

In [133]:
x=np.arange(10)
n=4
y=np.empty(len(x)-n+1)
for i in range(0,len(x)-n+1):
    b=0
    for j in range(0,n):
        b=b+x[i+j]
    b=b/n
    y[i]=b
print(x)
print(y)   


[0 1 2 3 4 5 6 7 8 9]
[1.5 2.5 3.5 4.5 5.5 6.5 7.5]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [134]:
z=np.arange(10)
print(z)
n=4
y=np.ones((4,3))
j=2
print(y)
for i in range(0,n):
    y[i:i+1]=np.array((z[j-2],z[j-1],z[j]))
    j=j-1
print(y)    

[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [9. 0. 1.]
 [8. 9. 0.]
 [7. 8. 9.]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [135]:
x=np.arange(10)
for i in range(len(x)):
    x[i]=x[i]*(-1)
print(x)    

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


Посчитать ранг матрицы

In [136]:
x=np.random.uniform(0,1,(10,10))
rank=np.linalg.matrix_rank(x)
print(rank)

10


Найти наиболее частое значение в массиве

In [86]:
x=np.random.randint(0,10,10)
print(x)
print(np.bincount(x))
print(np.bincount(x).argmax())

[3 1 0 5 9 4 2 6 9 9]
[1 1 1 1 1 1 1 0 0 3]
9


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [9]:
global x
x= np.random.randint(1, 11, size=(10,10))
print(x)
def tritri(inach,ikont,jnach,jkont):
    k=-1
    a=np.ones((3,3))
    for i in range(inach,ikont):
        k=k+1
        l=0
        for j in range(jnach,jkont):
            a[k,l]=x[i,j]
            l=l+1
    return(a)      
for i in range(0,8):
    j=i+3
    for k in range(0,8):
        m=k+3
        print(tritri(i,j,k,m))
    

[[10  3 10  6  9  4  1  6  2  3]
 [10  2  8  5  4  7  7  3  4  9]
 [ 8  1  5  1  9  8 10  6  6  2]
 [ 1  1  4 10  8  3  4  5  7  5]
 [ 8  9 10 10 10  1  2  8  2  6]
 [ 5  4  7  7  8  3  6 10  7  4]
 [ 5  5  9  7  1  9  1  3  8  8]
 [ 9  5  1  4  7  7  8  3  7  4]
 [10  8  8  8 10  9  8  2  1  4]
 [ 7  2  7  3  5  6 10  3  1  6]]
[[10.  3. 10.]
 [10.  2.  8.]
 [ 8.  1.  5.]]
[[ 3. 10.  6.]
 [ 2.  8.  5.]
 [ 1.  5.  1.]]
[[10.  6.  9.]
 [ 8.  5.  4.]
 [ 5.  1.  9.]]
[[6. 9. 4.]
 [5. 4. 7.]
 [1. 9. 8.]]
[[ 9.  4.  1.]
 [ 4.  7.  7.]
 [ 9.  8. 10.]]
[[ 4.  1.  6.]
 [ 7.  7.  3.]
 [ 8. 10.  6.]]
[[ 1.  6.  2.]
 [ 7.  3.  4.]
 [10.  6.  6.]]
[[6. 2. 3.]
 [3. 4. 9.]
 [6. 6. 2.]]
[[10.  2.  8.]
 [ 8.  1.  5.]
 [ 1.  1.  4.]]
[[ 2.  8.  5.]
 [ 1.  5.  1.]
 [ 1.  4. 10.]]
[[ 8.  5.  4.]
 [ 5.  1.  9.]
 [ 4. 10.  8.]]
[[ 5.  4.  7.]
 [ 1.  9.  8.]
 [10.  8.  3.]]
[[ 4.  7.  7.]
 [ 9.  8. 10.]
 [ 8.  3.  4.]]
[[ 7.  7.  3.]
 [ 8. 10.  6.]
 [ 3.  4.  5.]]
[[ 7.  3.  4.]
 [10.  6.  6.]
 [ 4.  5.  7.

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [53]:
x=10 
y=20
a=np.ones((x,y,y))
b=np.ones((x,y,1))
c=np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(c)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [31]:
global x
x=np.ones((16,16))
def dot(inach,ikont,jnach,jkont):
    count=0
    for i in range(inach,ikont):
        for j in range(jnach,jkont):
            count=count+x[i,j]
    return(count)
for i in range(0,16,4):
    j=i+4
    for k in range(0,16,4):
        m=k+4
        print(dot(i,j,k,m))


16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0
16.0


Найти n наибольших значений в массиве

In [2]:
x=np.arange(10)
y=np.sort(x)
n=4
z=np.ones(n)
c=len(x)-1
for i in range(0,n):
    z[i]=x[c]
    c=c-1
print(z)    
    
        
    

[9. 8. 7. 6.]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [15]:
def dot(arrays):
    arrays=[np.asarray(a) for a in arrays]
    shape=map(len,arrays)
    ix=np.indices(shape,dtype=int)
    ix=ix.reshape(len(arrays),-1).T
    for n, arr in enumerate(arrays):
        ix[:,n]=arrays[n][ix[:,n]]
    return ix
print(dot(([1, 2, 3], [4, 5])))

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [72]:
a=np.random.randint(1, 9, size=(8,3))
b=np.random.randint(1, 11, size=(2,2))
print(a)
print(b)
for i in range(0,8):
    m=0
    for j in range(0,3):
        for k in range(0,2):
            if (k==1)&(m==0):
                break
            for l in range(0,2):
                if (a[i,j]==b[k,l]):
                    m=m+1
                    
    if (m>=2):
        print("Строка",i,"имеет элементы строки b")
        

[[8 4 6]
 [4 1 8]
 [5 1 1]
 [5 1 6]
 [1 3 8]
 [4 1 2]
 [1 5 7]
 [6 6 3]]
[[10  4]
 [ 5  1]]
Строка 1 имеет элементы строки b
Строка 5 имеет элементы строки b


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [62]:
x= np.random.randint(1, 11, size=(10,3))
print(x)
j=0
for i in range(0,10):
    a=x[i,j]
    if (a!=x[i,j+1]):
        print(x[i,j:])
    else:
         if (a!=x[i,j+2]):
                print(x[i,j:])

[[ 8  7  2]
 [ 1  1  4]
 [ 1  1  5]
 [ 5  5  8]
 [ 3  6  4]
 [ 1  2  1]
 [ 4  3  5]
 [ 2  5  2]
 [ 3  9  4]
 [ 1  7 10]]
[8 7 2]
[1 1 4]
[1 1 5]
[5 5 8]
[3 6 4]
[1 2 1]
[4 3 5]
[2 5 2]
[3 9 4]
[ 1  7 10]


Преобразовать вектор чисел в матрицу бинарных представлений

In [11]:
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0]]


Дан двумерный массив. Найти все различные строки

In [52]:
x= np.random.randint(1, 11, size=(10,3))
print(x)
k=0
l=0
for i in range(0,10):
    for k in range(1,10):
        l=0
        m=0
        for j in range(0,3):
            if (x[i,j]==x[k,l]):
                m=m+1
                l=l+1
        if (m!=3):
            print("строки",i,"и",k,"различны")
            
        
            
                        
            
        

    

[[ 6 10  9]
 [ 4  1  8]
 [ 5  5  9]
 [ 1  6  8]
 [ 8  4  5]
 [ 7 10  4]
 [10  9  1]
 [ 4  1  2]
 [10  7  6]
 [ 8  6  1]]
строки 0 и 1 различны
строки 0 и 2 различны
строки 0 и 3 различны
строки 0 и 4 различны
строки 0 и 5 различны
строки 0 и 6 различны
строки 0 и 7 различны
строки 0 и 8 различны
строки 0 и 9 различны
строки 1 и 2 различны
строки 1 и 3 различны
строки 1 и 4 различны
строки 1 и 5 различны
строки 1 и 6 различны
строки 1 и 7 различны
строки 1 и 8 различны
строки 1 и 9 различны
строки 2 и 1 различны
строки 2 и 3 различны
строки 2 и 4 различны
строки 2 и 5 различны
строки 2 и 6 различны
строки 2 и 7 различны
строки 2 и 8 различны
строки 2 и 9 различны
строки 3 и 1 различны
строки 3 и 2 различны
строки 3 и 4 различны
строки 3 и 5 различны
строки 3 и 6 различны
строки 3 и 7 различны
строки 3 и 8 различны
строки 3 и 9 различны
строки 4 и 1 различны
строки 4 и 2 различны
строки 4 и 3 различны
строки 4 и 5 различны
строки 4 и 6 различны
строки 4 и 7 различны
строки 4 и 8 различны

Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [17]:
A=[1,2,3,4]
B=[5,6,7,8]
print(np.einsum('i->', A))       #sum
print(np.einsum('i,i->i', A, B)) 
print(np.einsum('i,i', A, B))    #внутр произв
print(np.einsum('i,j', A, B))   #внешн произв

10
[ 5 12 21 32]
70
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]
