Московский Авиационный Институт  
                                  (Национальный Исследовательский Университет)  



Кафедра 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»        



                                        -------------------------------
                                        Лабораторная работа по pandas №2  
                                        -------------------------------    



                                                                            Группа: М8О-103М-20  
                                                                            Студент: Галюгин Алексей Дмитриевич  
                                                                            Преподаватель: Поповкин Александр Викторович  



                                                 Москва, 2020  

In [2]:
import sys
import numpy as np
import pandas as pd

Получить от объекта Series показатели описательной статистики

In [4]:
state = np.random.RandomState(42)
x = pd.Series(state.normal(10, 5, 25))
print(x)
pkz = x.describe()
print(pkz)

0     12.483571
1      9.308678
2     13.238443
3     17.615149
4      8.829233
5      8.829315
6     17.896064
7     13.837174
8      7.652628
9     12.712800
10     7.682912
11     7.671351
12    11.209811
13     0.433599
14     1.375411
15     7.188562
16     4.935844
17    11.571237
18     5.459880
19     2.938481
20    17.328244
21     8.871118
22    10.337641
23     2.876259
24     7.278086
dtype: float64
count    25.000000
mean      9.182460
std       4.782765
min       0.433599
25%       7.188562
50%       8.829315
75%      12.483571
max      17.896064
dtype: float64


Узнать частоту уникальных элементов объекта Series (гистограмма)

In [66]:
data='abcdefghik'
len_series=30
x=pd.Series(np.take(list(data), np.random.randint(len(data), size=len_series)))
print(x) 
ans=x.value_counts()
 
print(ans)

0     a
1     g
2     k
3     h
4     i
5     h
6     b
7     h
8     c
9     b
10    a
11    b
12    k
13    i
14    f
15    g
16    h
17    k
18    f
19    d
20    c
21    a
22    f
23    f
24    d
25    g
26    h
27    e
28    e
29    d
dtype: object
h    5
f    4
d    3
b    3
k    3
g    3
a    3
e    2
i    2
c    2
dtype: int64


Заменить все элементы объекта Series на "Other", кроме двух наиболее часто встречающихся

In [57]:
data='abcdefghik'
len_series=30
x=pd.Series(np.take(list(data), np.random.randint(len(data), size=len_series)))
print(x.value_counts())
x[~x.isin(x.value_counts().index[:2])] = 'Other'
print(x)

e    4
b    4
k    4
a    4
d    3
h    3
i    2
c    2
f    2
g    2
dtype: int64
0         b
1         b
2     Other
3     Other
4         e
5     Other
6     Other
7     Other
8     Other
9     Other
10    Other
11    Other
12        e
13        e
14    Other
15    Other
16    Other
17        b
18        b
19    Other
20    Other
21    Other
22        e
23    Other
24    Other
25    Other
26    Other
27    Other
28    Other
29    Other
dtype: object


Создать объект Series в индексах дата каждый день 2019 года, в значениях случайное значение

In [7]:
x = pd.Series(pd.date_range(start='2019-01-01', end='2019-12-31', freq='D')) 
y = pd.Series(np.random.rand(len(x)), index=x)
print(y)

2019-01-01    0.534247
2019-01-02    0.589179
2019-01-03    0.814931
2019-01-04    0.383411
2019-01-05    0.176373
                ...   
2019-12-27    0.861208
2019-12-28    0.738458
2019-12-29    0.134971
2019-12-30    0.256372
2019-12-31    0.735867
Length: 365, dtype: float64


Найти сумму всех вторников

In [8]:
ans1 = y[y.index.weekday == 2].sum()
print('Сумма всех вторников =', ans1)
print()

Сумма всех вторников = 22.89198919178515



Для каждого месяца найти среднее значение

In [9]:
mean=y.resample('M').mean()
print('Среднее =',mean)

Среднее = 2019-01-31    0.444537
2019-02-28    0.552651
2019-03-31    0.432992
2019-04-30    0.376895
2019-05-31    0.461805
2019-06-30    0.431908
2019-07-31    0.479550
2019-08-31    0.478881
2019-09-30    0.452954
2019-10-31    0.527409
2019-11-30    0.576384
2019-12-31    0.438491
Freq: M, dtype: float64


Преобразовать объект Series в DataFrame заданной формы (shape)

In [8]:
x=pd.Series(np.random.randint(low=1, high=10, size=[35]))
print(x)
y=(7, 5)
z=pd.DataFrame(x.values.reshape(y))
print(z)

0     7
1     6
2     1
3     6
4     2
5     5
6     7
7     5
8     7
9     2
10    7
11    2
12    7
13    1
14    4
15    2
16    8
17    6
18    3
19    6
20    3
21    2
22    5
23    8
24    5
25    9
26    8
27    6
28    7
29    1
30    9
31    9
32    1
33    5
34    3
dtype: int32
[7 6 1 6 2 5 7 5 7 2 7 2 7 1 4 2 8 6 3 6 3 2 5 8 5 9 8 6 7 1 9 9 1 5 3]
   0  1  2  3  4
0  7  6  1  6  2
1  5  7  5  7  2
2  7  2  7  1  4
3  2  8  6  3  6
4  3  2  5  8  5
5  9  8  6  7  1
6  9  9  1  5  3


Найти индексы объекта Series кратные 3

In [10]:
x=pd.Series([1,2,3,4,5,6,7,8,9])
y=np.where(x%3==0)[0]
print(y)

[2 5 8]


Получить данные по индексам объекта Series

In [12]:
u= pd.Series(list('fdgdgdfgdhgfhgfhgvgfhfg'))
p = [0, 4, 8, 14, 20, 10]
print(u[p]) 

0     f
4     g
8     d
14    f
20    h
10    g
dtype: object


Объединить два объекта Series вертикально и горизонтально

In [75]:
a = pd.Series(range(5))
b = pd.Series(list('abcde'))
c = pd.concat([a, b],axis=1)
print(c)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


Получить индексы объекта Series A, данные которых содержатся в объетке Series B

In [4]:
A=pd.Series([1,4,2,6,7,8,3,2,9])
B=pd.Series([0,6,7,3,2,1,4,5,3])
Z=np.where(A.isin(B))[0]
print(Z)

[0 1 2 3 4 6 7]


Получить объект Series B, котоырй содержит элементы без повторений объекта A

In [26]:
A=pd.Series([1,4,2,6,7,8,3,2,9,3,9])
B=pd.Series(A.unique())
print(B)

0    1
1    4
2    2
3    6
4    7
5    8
6    3
7    9
dtype: int64


Преобразовать каждый символ объекта Series в верхний регистр

In [35]:
x=pd.Series(['d','f','a'])
z = pd.Series(i.title() for i in x)
print(z)

0    D
1    F
2    A
dtype: object


Преобразовать данных Series в строку

In [38]:
x=pd.Series(['d','f','a'])
y=''.join(x)
print(y)

dfa


Рассчитать количество символов в объекте Series

In [48]:
x=pd.Series('dakldasklsdaklj')
print(x)
y=pd.Series(len(i) for i in x)
print(y)
z=''.join(x)
print(z)

0    dakldasklsdaklj
dtype: object
0    15
dtype: int64
dakldasklsdaklj


Найти разность между объектом Series и смещением объекта Series на n

In [49]:
x=pd.Series([1,2,4,5,6,13,4,35,10])
n=2
y=x.diff(periods=n)
print(y)

0     NaN
1     NaN
2     3.0
3     3.0
4     2.0
5     8.0
6    -2.0
7    22.0
8     6.0
dtype: float64


Преобразовать разные форматы строк объекта Series в дату

In [104]:
x=pd.Series(['2018-02-09', '10.04.2020', '2019 15 Dec'])
print(pd.to_datetime(x))

0   2018-02-09
1   2020-10-04
2   2019-12-15
dtype: datetime64[ns]


Поскольку работа с датой часто встречается в работе, то см. еще один пример
все данные должны иметь одинаковый формат (часто бывает выгрузка из SQL)

In [84]:
x=pd.Series(['2018.09.09','2012.04.06','2013.12.12','2015.11.11'])
y=pd.to_datetime(x,format='%Y.%m.%d')
print(y)

0   2018-09-09
1   2012-04-06
2   2013-12-12
3   2015-11-11
dtype: datetime64[ns]


Получить год, месяц, день, день недели, номер дня в году от объекта Series (string). Распарсить в дату и время

In [99]:
from dateutil.parser import parse
x=pd.Series(['2018.11.18','2016.04.25','2013.11.11','2012.12.12'])
y=x.map(lambda z:parse(z, yearfirst=True))
print(y)
print(y.dt.year)
print(y.dt.month)
print(y.dt.day)
print(y.dt.weekofyear)
print(y.dt.dayofyear)

0   2018-11-18
1   2016-04-25
2   2013-11-11
3   2012-12-12
dtype: datetime64[ns]
0    2018
1    2016
2    2013
3    2012
dtype: int64
0    11
1     4
2    11
3    12
dtype: int64
0    18
1    25
2    11
3    12
dtype: int64
0    46
1    17
2    46
3    50
dtype: int64
0    322
1    116
2    315
3    347
dtype: int64


Отобрать элементы объекта Series, кторые содержат не менее двух гласных

In [33]:
from collections import Counter
 
s = pd.Series(['hihihihi', 'abso', 'dom', 'cape'])
mask = s.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiouаоиеёэыуюя')]) >= 2)
ans = s[mask]
print(ans)

0    hihihihi
1        abso
3        cape
dtype: object


Отобрать e-маилы из объекта Series (можно юзать регулярки)

In [37]:
import re
 
emails = pd.Series(['test text @test.com', 'test@mail.ru', 'test.2ru', 'test@pp'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
ans = emails[mask]
print(ans)

1    test@mail.ru
dtype: object


Получить среднее значение каждого уникального объекта Series s1 через "маску" другого объекта Series s2

In [82]:
n = 10
x = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], n))
print(x)
y = pd.Series(np.linspace(1,n,n))
print(y)
z = y.groupby(x)
k=pd.Series(y.groupby(x))
print(k)
y=z.mean()
print(y)

0      dog
1      dog
2      dog
3      cat
4      dog
5     bird
6    horse
7      cat
8    horse
9      dog
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
0                        (bird, [6.0])
1                    (cat, [4.0, 8.0])
2    (dog, [1.0, 2.0, 3.0, 5.0, 10.0])
3                  (horse, [7.0, 9.0])
dtype: object
bird     6.0
cat      6.0
dog      4.2
horse    8.0
dtype: float64
