Московский Авиационный Институт  
                                  (Национальный Исследовательский Университет)  



Кафедра 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»        



                                        -------------------------------
                                        Лабораторная работа по pandas №3  
                                        -------------------------------    



                                                                            Группа: М8О-103М-20  
                                                                            Студент: Галюгин Алексей Дмитриевич  
                                                                            Преподаватель: Поповкин Александр Викторович  



                                                 Москва, 2020  

In [2]:
import sys
import numpy as np
import pandas as pd

Найти евклидово расстоняие между двумя объектами Series

In [11]:
from scipy.spatial import distance
n=3
s1=pd.Series(np.array([1, 2, 3, 4, 5, 6]))
s2=pd.Series(np.array([0, 2, 3, 4, 5, 7]))
print(s1)
print(s2)
ans1 = sum((s1-s2)**2)**0.5
print(ans1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32
0    0
1    2
2    3
3    4
4    5
5    7
dtype: int32
1.4142135623730951


Найти индексы локальных максимумов в объекте Series

In [4]:
s=pd.Series([1, 5, 7, 11, 8, 4, 12, 5, 8, 16, 8])
x=np.diff(s)
y=np.sign(x)
z=np.diff(y)
print(x)
print(y)
print(z)
ans = np.where(z == -2)[0]+1
print(ans)

[ 4  2  4 -3 -4  8 -7  3  8 -8]
[ 1  1  1 -1 -1  1 -1  1  1 -1]
[ 0  0 -2  0  2 -2  2  0 -2]
[3 6 9]


Заменить пробелы наименее часто встречающимся символов

In [31]:
str_test = 'bnb ber kekb dare'
 
s = pd.Series(list(str_test))
freq = s.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
print(least_freq)
str_test=''.join(s.replace(' ', least_freq))
print(str_test)

b    4
     3
e    3
r    2
k    2
a    1
n    1
d    1
dtype: int64
d
bnbdberdkekbddare


 Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10

In [35]:

s=pd.Series(np.random.randint(low=1,high=10,size=[10]), pd.date_range('2018-01-01', periods=10, freq='W-SAT'))
print(s)

2018-01-06    6
2018-01-13    6
2018-01-20    8
2018-01-27    8
2018-02-03    8
2018-02-10    8
2018-02-17    5
2018-02-24    6
2018-03-03    1
2018-03-10    3
Freq: W-SAT, dtype: int32


Заполнить пропущенные даты, значением выше (заполненной даты)

In [50]:
s = pd.Series([2, 5, 8, np.nan], index=pd.to_datetime(['2018-01-01', '2018-01-03', '2018-01-06', '2018-01-08']))
print(s)
ans = s.resample('D').ffill()
print(ans)

2018-01-01    2.0
2018-01-03    5.0
2018-01-06    8.0
2018-01-08    NaN
dtype: float64
2018-01-01    2.0
2018-01-02    2.0
2018-01-03    5.0
2018-01-04    5.0
2018-01-05    5.0
2018-01-06    8.0
2018-01-07    8.0
2018-01-08    NaN
Freq: D, dtype: float64


Вычислить автокорреляцию объекта Series

In [55]:
n=20
 
s=pd.Series(np.arange(n))
s=s + np.random.normal(1, 3, n)
k=s.autocorr()
print(k)

0.7504132682558335
